ITEM.name = "Nightvision Goggles"
ITEM.desc = "Allow you to see in the dark."
ITEM.model = "models/props_combine/combinebutton.mdl"
ITEM.class = "sh_nvg"
ITEM.weaponCategory = "Equipment"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 300
ITEM.category = "Equipment"