FACTION.name = "Metro Dweller"
FACTION.desc = "Commonfolk of the Metro"
FACTION.color = Color(126, 80, 21)
FACTION.isDefault = true

FACTION.models = {
"models/half-dead/metrollfix/a1b1.mdl", -- Metro Last Light Citizens
"models/half-dead/metrollfix/a2b1.mdl",
"models/half-dead/metrollfix/a3b1.mdl",
"models/half-dead/metrollfix/a4b1.mdl",
"models/half-dead/metrollfix/a5b1.mdl",
"models/half-dead/metrollfix/a6b1.mdl",
"models/half-dead/metrollfix/m1b1.mdl",
"models/half-dead/metrollfix/m2b1.mdl",
"models/half-dead/metrollfix/m3b1.mdl",
"models/half-dead/metrollfix/m4b1.mdl",
"models/half-dead/metrollfix/m5b1.mdl",
"models/half-dead/metrollfix/m6b1.mdl",
"models/half-dead/metrollfix/m7b1.mdl",
"models/half-dead/metrollfix/m8b1.mdl",
"models/half-dead/metrollfix/m9b1.mdl",
"models/half-dead/metrollfix/f1b1.mdl",
"models/half-dead/metrollfix/f2b1.mdl",
"models/half-dead/metrollfix/f3b1.mdl",
"models/half-dead/metrollfix/f4b1.mdl",
"models/half-dead/metrollfix/f6b1.mdl",
"models/half-dead/metrollfix/f7b1.mdl",
"models/tnb/stalker/male_00_anorak.mdl",
"models/tnb/stalker/male_01_anorak.mdl",
"models/tnb/stalker/male_02_anorak.mdl",
"models/tnb/stalker/male_03_anorak.mdl",
"models/tnb/stalker/male_04_anorak.mdl",
"models/tnb/stalker/male_05_anorak.mdl",
"models/tnb/stalker/male_06_anorak.mdl",
"models/tnb/stalker/male_07_anorak.mdl",
"models/tnb/stalker/male_08_anorak.mdl",
"models/tnb/stalker/male_09_anorak.mdl",
"models/tnb/stalker/male_10_anorak.mdl",
"models/tnb/stalker/male_11_anorak.mdl",
"models/tnb/stalker/male_12_anorak.mdl",
"models/tnb/stalker/male_13_anorak.mdl",
"models/tnb/stalker/male_18_anorak.mdl",
"models/ninja/signalvariance/act_fedor_bomj_a3.mdl",
"models/ninja/signalvariance/act_fedor_bomj_artyom.mdl",
"models/ninja/signalvariance/act_fedor_bomj_bf4.mdl",
"models/ninja/signalvariance/act_fedor_hunter.mdl",
"models/tnb/stalker/female_01_anorak.mdl", -- New Female Models
"models/tnb/stalker/female_02_anorak.mdl",
"models/tnb/stalker/female_03_anorak.mdl",
"models/tnb/stalker/female_04_anorak.mdl",
"models/tnb/stalker/female_05_anorak.mdl",
"models/tnb/stalker/female_06_anorak.mdl",
"models/tnb/stalker/female_07_anorak.mdl",
"models/tnb/stalker/female_08_anorak.mdl",
"models/tnb/stalker/female_10_anorak.mdl",
"models/tnb/stalker/female_11_anorak.mdl",
"models/tnb/stalker/female_13_anorak.mdl",
"models/dizcordum/citizens/female_01.mdl",
"models/dizcordum/citizens/female_02.mdl",
"models/dizcordum/citizens/female_03.mdl",
"models/dizcordum/citizens/female_04.mdl",
"models/dizcordum/citizens/female_05.mdl",
"models/dizcordum/citizens/female_06.mdl",
"models/dizcordum/citizens/female_07.mdl",
"models/dizcordum/citizens/female_08.mdl",
"models/dizcordum/citizens/female_09.mdl"
}

FACTION_DWELLER = FACTION.index
