PLUGIN.name="Model fixes"
PLUGIN.author="dickmosi i guess"
PLUGIN.desc="Fixes certain models that T-Pose by default"

--[[
citizen_male				A male NPC citizen model from Half-Life 2.
citizen_female			A female NPC citizen model from Half-Life 2.
metrocop					A metropolice NPC model from Half-Life 2.
overwatch					A Combine soldier NPC model from Half-Life 2.
vort							A vortigaunt NPC model from Half-Life 2.
player						A normal Garry's Mod player model. Player model paths normally start with nut.anim.setModelClass("models/player.
zombie						A zombie NPC model from Half-Life 2.
fastZombie				A fast zombie NPC model from Half-Life 2.
]]

-- TnB Stalker Models

nut.anim.setModelClass("models/tnb/stalker/female_01_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_01_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_02_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_02_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_03_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_03_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_04_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_04_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_05_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_05_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_06_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_06_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_07_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_07_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_08_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_08_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_sunrise_balaclava.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_sunrise_combat.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_sunrise_gasmask.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_sunrise_helmet.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_00_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_00_skat.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_00_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_00_sunrise_exo.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_01_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_01_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_02_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_02_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_03_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_03_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_04_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_04_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_05_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_05_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_06_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_06_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_07_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_07_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_08_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_08_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_09_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_09_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_10_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_10_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_bandit.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_bandit_gasmask.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_bandit_skat.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_berill.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_berill_helmet.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_berill_seva.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_cs1.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_cs2.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_cs2_helmet.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_cs3.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_cs3_mask.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_cs4.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_exo.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_exo_bandit.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_io7a.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_io7a_bandit.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_io8a.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_radsuit.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_radsuit_bandit.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_radsuit_seva.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_radsuit_tubes.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_seva.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_seva_chestplate.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_seva_cs4.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_skat.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_skat_bulat.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_skat_exo.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_ssp.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_sunrise_balaclava.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_sunrise_combat.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_sunrise_gasmask.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_sunrise_helmet.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_sunrise_pracs.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_sunrise_winter.mdl", "player")

-- TnB Donator Models

nut.anim.setModelClass("models/tnb/stalker/female_09_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_09_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_10_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_10_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_11_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_11_radsuit.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_11_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_12_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_12_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_13_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/female_13_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_11_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_11_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_12_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_12_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_13_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_13_radsuit.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_13_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_14_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_14_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_15_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_15_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_16_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_16_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_17_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_17_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_18_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_18_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_19_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_19_skat.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_19_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_20_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_20_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_21_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_21_skat.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_21_sunrise.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_21_sunrise_exo.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_22_anorak.mdl", "player")
nut.anim.setModelClass("models/tnb/stalker/male_22_sunrise.mdl", "player")